<?php

// info begin
// Generated by script 2014-06-03 13:51:16, 
// based on file "N:\Felles\Forurensning\2. Internasjonalt arbeid\2012. Uganda\Kravspek\Databasefields for EIA database NEMA version 0.33.xlsx".
// info end

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTables extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
			DB::statement('SET FOREIGN_KEY_CHECKS=0;');		
				
// up begin
Schema::create('additional_districts', function(Blueprint $table)
{
	$table->increments('id');
	$table->integer('district_id')->unsigned()->nullable(); 
	$table->foreign('district_id')->references('id')->on('districts');
	$table->integer('project_id')->unsigned()->nullable(); 
	$table->foreign('project_id')->references('id')->on('projects');
});


Schema::create('audits_inspections', function(Blueprint $table)
{
	$table->increments('id');
	$table->integer('year')->unsigned()->nullable();
	$table->integer('type_control')->unsigned()->nullable();
	$table->integer('user_id')->unsigned()->nullable(); 
	$table->foreign('user_id')->references('id')->on('users');
	$table->date('date_control')->nullable();
	$table->date('date_report_sent')->nullable();
	$table->string('recommendations', 2000)->nullable();
	$table->string('follow_up', 255)->nullable();
	$table->date('date_deadline')->nullable();
	$table->date('date_submitted')->nullable();
	$table->date('date_closing_letter')->nullable();
	$table->integer('project_id')->unsigned()->nullable(); 
	$table->foreign('project_id')->references('id')->on('projects');
	$table->string('remarks', 2000)->nullable();
	$table->softDeletes();
	$table->string('created_by', 255)->nullable();
	$table->string('updated_by', 255)->nullable();
	$table->timestamps();
});


Schema::create('categories', function(Blueprint $table)
{
	$table->increments('id');
	$table->string('description_short', 255)->nullable();
	$table->string('description_long', 2000)->nullable();
	$table->integer('consequence')->unsigned()->nullable();
	$table->boolean('is_passive')->default(false)->nullable();
});


Schema::create('codes', function(Blueprint $table)
{
	$table->increments('id');
	$table->string('description1', 255)->nullable();
	$table->string('description2', 255)->nullable();
	$table->integer('value1')->unsigned()->nullable();
	$table->string('dropdown_list', 255)->nullable();
	$table->boolean('is_passive')->default(false)->nullable();
});


Schema::create('documents', function(Blueprint $table)
{
	$table->increments('id');
	$table->date('date_submitted')->nullable();
	$table->integer('sub_final')->unsigned()->nullable();
	$table->integer('sub_copy_no')->unsigned()->nullable();
	$table->string('title', 255)->nullable();
	$table->integer('type')->unsigned()->nullable();
	$table->integer('number')->unsigned()->nullable();
	$table->string('code', 255)->nullable();
	$table->string('consultent', 255)->nullable();
	$table->integer('director_copy_no')->unsigned()->nullable();
	$table->date('date_sent_director')->nullable();
	$table->integer('coordinator_copy_no')->unsigned()->nullable();
	$table->date('date_copies_coordinator')->nullable();
	$table->date('date_next_appointment')->nullable();
	$table->date('date_sent_from_dep')->nullable();
	$table->date('date_sent_officer')->nullable();
	$table->string('folio_no', 255)->nullable();
	$table->integer('conclusion')->unsigned()->nullable();
	$table->integer('eia_permit_id')->unsigned()->nullable(); 
	$table->foreign('eia_permit_id')->references('id')->on('eias_permits');
	$table->integer('control_id')->unsigned()->nullable();
	$table->string('remarks', 2000)->nullable();
	$table->softDeletes();
	$table->string('created_by', 255)->nullable();
	$table->string('updated_by', 255)->nullable();
	$table->timestamps();
});


Schema::create('districts', function(Blueprint $table)
{
	$table->increments('id');
	$table->string('district', 255)->nullable();
	$table->string('hasc', 255)->nullable();
	$table->integer('iso')->unsigned()->nullable();
	$table->string('fips', 255)->nullable();
	$table->string('region', 255)->nullable();
	$table->softDeletes();
	$table->string('created_by', 255)->nullable();
	$table->string('updated_by', 255)->nullable();
	$table->timestamps();
});


Schema::create('eias_permits', function(Blueprint $table)
{
	$table->increments('id');
	$table->integer('project_id')->unsigned()->nullable(); 
	$table->foreign('project_id')->references('id')->on('projects');
	$table->integer('teamleader_id')->unsigned()->nullable();
	$table->integer('cost')->unsigned()->nullable();
	$table->integer('status')->unsigned()->nullable();
	$table->integer('user_id')->unsigned()->nullable(); 
	$table->foreign('user_id')->references('id')->on('users');
	$table->integer('inspection_recommended')->unsigned()->nullable();
	$table->date('date_inspection')->nullable();
	$table->string('officer_recommend', 2000)->nullable();
	$table->decimal('fee', 24, 6)->nullable();
	$table->date('date_sent_ded_approval')->nullable();
	$table->integer('decision')->unsigned()->nullable();
	$table->date('date_decision')->nullable();
	$table->date('date_fee_notification')->nullable();
	$table->date('date_fee_payed')->nullable();
	$table->string('fee_receipt_no', 255)->nullable();
	$table->integer('designation')->unsigned()->nullable();
	$table->date('date_certificate')->nullable();
	$table->integer('certificate_no')->unsigned()->nullable();
	$table->date('date_cancelled')->nullable();
	$table->string('remarks', 2000)->nullable();
	$table->softDeletes();
	$table->string('created_by', 255)->nullable();
	$table->string('updated_by', 255)->nullable();
	$table->timestamps();
});


Schema::create('hearings', function(Blueprint $table)
{
	$table->increments('id');
	$table->integer('lead_agency')->unsigned()->nullable();
	$table->integer('district_id')->unsigned()->nullable(); 
	$table->foreign('district_id')->references('id')->on('districts');
	$table->date('date_dispatched')->nullable();
	$table->date('date_expected')->nullable();
	$table->date('date_received')->nullable();
	$table->string('recommendations', 2000)->nullable();
	$table->integer('document_id')->unsigned()->nullable(); 
	$table->foreign('document_id')->references('id')->on('documents');
	$table->string('remarks', 2000)->nullable();
	$table->softDeletes();
	$table->string('created_by', 255)->nullable();
	$table->string('updated_by', 255)->nullable();
	$table->timestamps();
});


Schema::create('organisations', function(Blueprint $table)
{
	$table->increments('id');
	$table->integer('tin')->unsigned()->nullable();
	$table->string('name', 255)->nullable();
	$table->string('visiting_address', 255)->nullable();
	$table->integer('box_no')->unsigned()->nullable();
	$table->string('city', 255)->nullable();
	$table->string('phone', 255)->nullable();
	$table->string('fax', 255)->nullable();
	$table->string('email', 255)->nullable();
	$table->string('contact_person', 255)->nullable();
	$table->string('remarks', 2000)->nullable();
	$table->softDeletes();
	$table->string('created_by', 255)->nullable();
	$table->string('updated_by', 255)->nullable();
	$table->timestamps();
});


Schema::create('practitioner_certificates', function(Blueprint $table)
{
	$table->increments('id');
	$table->integer('practitioner_id')->unsigned()->nullable(); 
	$table->foreign('practitioner_id')->references('id')->on('practitioners');
	$table->integer('year')->unsigned()->nullable();
	$table->date('date_of_entry')->nullable();
	$table->integer('cert_type')->unsigned()->nullable();
	$table->integer('number')->unsigned()->nullable();
	$table->string('cert_no', 255)->nullable();
	$table->integer('conditions')->unsigned()->nullable();
	$table->boolean('is_cancelled')->default(false)->nullable();
	$table->string('remarks', 2000)->nullable();
	$table->softDeletes();
	$table->string('created_by', 255)->nullable();
	$table->string('updated_by', 255)->nullable();
	$table->timestamps();
});


Schema::create('practitioners', function(Blueprint $table)
{
	$table->increments('id');
	$table->string('person', 255)->nullable();
	$table->integer('tin')->unsigned()->nullable();
	$table->string('organisation_name', 255)->nullable();
	$table->string('visiting_address', 255)->nullable();
	$table->integer('box_no')->unsigned()->nullable();
	$table->string('city', 255)->nullable();
	$table->string('phone', 255)->nullable();
	$table->string('fax', 255)->nullable();
	$table->string('email', 255)->nullable();
	$table->string('qualifications', 2000)->nullable();
	$table->string('expertise', 2000)->nullable();
	$table->string('remarks', 2000)->nullable();
	$table->softDeletes();
	$table->string('created_by', 255)->nullable();
	$table->string('updated_by', 255)->nullable();
	$table->timestamps();
});


Schema::create('projects', function(Blueprint $table)
{
	$table->increments('id');
	$table->string('title', 255)->nullable();
	$table->integer('category_id')->unsigned()->nullable(); 
	$table->foreign('category_id')->references('id')->on('categories');
	$table->integer('district_id')->unsigned()->nullable(); 
	$table->foreign('district_id')->references('id')->on('districts');
	$table->string('location', 255)->nullable();
	$table->decimal('longitude', 24, 6)->nullable();
	$table->decimal('latitude', 24, 6)->nullable();
	$table->integer('has_industrial_waste_water')->unsigned()->nullable();
	$table->integer('grade')->unsigned()->nullable();
	$table->integer('organisation_id')->unsigned()->nullable(); 
	$table->foreign('organisation_id')->references('id')->on('organisations');
	$table->string('remarks', 2000)->nullable();
	$table->softDeletes();
	$table->string('created_by', 255)->nullable();
	$table->string('updated_by', 255)->nullable();
	$table->timestamps();
});


Schema::create('team_members', function(Blueprint $table)
{
	$table->increments('id');
	$table->integer('practitioner_id')->unsigned()->nullable(); 
	$table->foreign('practitioner_id')->references('id')->on('practitioners');
	$table->integer('eia_permit_id')->unsigned()->nullable(); 
	$table->foreign('eia_permit_id')->references('id')->on('eias_permits');
});


Schema::create('users', function(Blueprint $table)
{
	$table->increments('id');
	$table->string('initials', 255)->nullable();
	$table->string('full_name', 255)->nullable();
	$table->string('job_position_code', 255)->nullable();
	$table->string('job_position_name', 255)->nullable();
	$table->string('email', 255)->nullable();
	$table->string('password', 255)->nullable();
	$table->boolean('is_passive')->default(false)->nullable();
	$table->softDeletes();
	$table->string('created_by', 255)->nullable();
	$table->string('updated_by', 255)->nullable();
	$table->timestamps();
});


Schema::create('lead_agencies', function(Blueprint $table)
{
	$table->increments('id');
	$table->string('lead_agency_short', 255)->nullable();
	$table->string('lead_agency_long', 255)->nullable();
});


// up end

		DB::statement('SET FOREIGN_KEY_CHECKS=1;');
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		DB::statement('SET FOREIGN_KEY_CHECKS=0;');
// down begin
	Schema::dropIfExists('additional_districts', function(Blueprint $table){});
	Schema::dropIfExists('audits_inspections', function(Blueprint $table){});
	Schema::dropIfExists('categories', function(Blueprint $table){});
	Schema::dropIfExists('codes', function(Blueprint $table){});
	Schema::dropIfExists('documents', function(Blueprint $table){});
	Schema::dropIfExists('districts', function(Blueprint $table){});
	Schema::dropIfExists('eias_permits', function(Blueprint $table){});
	Schema::dropIfExists('hearings', function(Blueprint $table){});
	Schema::dropIfExists('organisations', function(Blueprint $table){});
	Schema::dropIfExists('practitioner_certificates', function(Blueprint $table){});
	Schema::dropIfExists('practitioners', function(Blueprint $table){});
	Schema::dropIfExists('projects', function(Blueprint $table){});
	Schema::dropIfExists('team_members', function(Blueprint $table){});
	Schema::dropIfExists('users', function(Blueprint $table){});
	Schema::dropIfExists('lead_agencies', function(Blueprint $table){});
// down end
	DB::statement('SET FOREIGN_KEY_CHECKS=1;');
	}	

}
