<?php

// info begin
// Generated by script 2015-09-24 13:53:57, 
// based on file "N:\Felles\Forurensning\2. Internasjonalt arbeid\2012. Uganda\Kravspek\Tabeller\Supporting tables version 1.26.xlsx".
// info end

use Illuminate\Database\Seeder;
use \App\LeadAgency;
use \App\Category;
use \App\Code;
use \App\District;

class ExcelDataTableSeeder extends Seeder {
 
    public function run()
    {
        //DB::table('users')->truncate();
        //DB::table('assigned_roles')->truncate();
        //DB::table('permission_role')->truncate();    		
    		//DB::table('permissions')->truncate();        
        //DB::table('roles')->truncate();
        
        //DB::table('lead_agencies')->truncate();
        DB::table('categories')->truncate();
        //DB::table('codes')->truncate();
        //DB::table('districts')->truncate();
        //DB::table('practitioner_certificates')->truncate();
        //DB::table('practitioners')->truncate();
        //DB::table('organisations')->truncate();
        //DB::table('projects')->truncate();
        //DB::table('additional_districts')->truncate();

        
        //$permission1 = Permission::create(array('name' => 'Rettighet 1', 'display_name' => 'Rettighet 1'));
        //$permission2 = Permission::create(array('name' => 'Rettighet 2', 'display_name' => 'Rettighet 2'));
        //$role1->attachPermission($permission1);
        //$role2->attachPermission($permission1);
        //$role2->attachPermission($permission2);


        // seed begin
$category1 = Category::create(array(
  'id' => 1 ,
	'description_short' => " Education Facility" ,
	'description_long' => " Education Facility" ,
	'consequence' => 6             
));

$category2 = Category::create(array(
  'id' => 2 ,
	'description_short' => " Energy Production/Distribution" ,
	'description_long' => " Energy Production / Distribution" ,
	'consequence' => 6             
));

$category3 = Category::create(array(
  'id' => 3 ,
	'description_short' => " Fuel Station" ,
	'description_long' => " Fuel Station" ,
	'consequence' => 6             
));

$category4 = Category::create(array(
  'id' => 4 ,
	'description_short' => " Information & Communications Technology" ,
	'description_long' => " Information & Communications Technology" ,
	'consequence' => 6             
));

$category5 = Category::create(array(
  'id' => 5 ,
	'description_short' => " Infrastructure - Roads, Housing, Renovations" ,
	'description_long' => " Infrastructure - Roads, Housing, Renovations" ,
	'consequence' => 6             
));

$category6 = Category::create(array(
  'id' => 6 ,
	'description_short' => " Land-Use Change, Forestry, Agriculture" ,
	'description_long' => " Land-Use Change, Forestry, Agriculture, Livestock" ,
	'consequence' => 6             
));

$category7 = Category::create(array(
  'id' => 7 ,
	'description_short' => " Minerals, Mining, Quarry" ,
	'description_long' => " Minerals, Mining, Quarry" ,
	'consequence' => 6             
));

$category8 = Category::create(array(
  'id' => 8 ,
	'description_short' => " Miscellaneous Assessments - Policy, Plan …" ,
	'description_long' => " Miscellaneous Assessments - Policy, Plan, Programme" ,
	'consequence' => 6             
));

$category9 = Category::create(array(
  'id' => 9 ,
	'description_short' => " Oil and Gas" ,
	'description_long' => " Oil and Gas" ,
	'consequence' => 6             
));

$category10 = Category::create(array(
  'id' => 10 ,
	'description_short' => " Pest, Vector, Disease Control" ,
	'description_long' => " Pest, Vector, Disease Control" ,
	'consequence' => 6             
));

$category11 = Category::create(array(
  'id' => 11 ,
	'description_short' => " Processing, Manufacturing Industry" ,
	'description_long' => " Processing, Manufacturing Industry" ,
	'consequence' => 6             
));

$category12 = Category::create(array(
  'id' => 12 ,
	'description_short' => " Waste Management and Infrastructure" ,
	'description_long' => " Waste Management and Infrastructure" ,
	'consequence' => 6             
));

$category13 = Category::create(array(
  'id' => 13 ,
	'description_short' => " Water Supply Systems and Sanitation" ,
	'description_long' => " Water Supply Systems and Sanitation" ,
	'consequence' => 6             
));

$category14 = Category::create(array(
  'id' => 14 ,
	'description_short' => " Water Resources, Wetlands, Fisheries Mgnt" ,
	'description_long' => " Water Resources, Wetlands, Fisheries Management" ,
	'consequence' => 6             
));

$category15 = Category::create(array(
  'id' => 15 ,
	'description_short' => " Wildlife, Hotels, Leisure, Tourism Facility" ,
	'description_long' => " Wildlife, Hotels, Leisure, Tourism Facility" ,
	'consequence' => 6             
));

$category16 = Category::create(array(
  'id' => 16 ,
	'description_short' => "Clearing and farm construction" ,
	'description_long' => "Clearing and farm construction for individual subsistence smal farms" ,
	'consequence' => 7             
));

$category17 = Category::create(array(
  'id' => 17 ,
	'description_short' => "Construction or repair of individual houses" ,
	'description_long' => "Construction or repair of individual houses" ,
	'consequence' => 7             
));

$category18 = Category::create(array(
  'id' => 18 ,
	'description_short' => "Minor land use changes" ,
	'description_long' => "Minor land use changes in area with slopes less than 20 % including housing construction" ,
	'consequence' => 7             
));

$category19 = Category::create(array(
  'id' => 19 ,
	'description_short' => "Information collection" ,
	'description_long' => "Information collection (scientific or educational) exept if it involves use of chemicals or endangered species or alien materials" ,
	'consequence' => 7             
));

$category20 = Category::create(array(
  'id' => 20 ,
	'description_short' => "Transfer of ownership of land or facilities" ,
	'description_long' => "Transfer of ownership of land or related facilities so long as the general character of the area is not changed" ,
	'consequence' => 7             
));

$category21 = Category::create(array(
  'id' => 21 ,
	'description_short' => "Environmental enforcement actions" ,
	'description_long' => "Environmental enforcement actions" ,
	'consequence' => 7             
));

$category22 = Category::create(array(
  'id' => 22 ,
	'description_short' => "Emergency repairs to facilities" ,
	'description_long' => "Emergency repairs to facilities within the character of its surroundings" ,
	'consequence' => 7             
));

// seed end

/*

$organisation1 = Organisation::create(array(
	'name' => "Organisasjon nummer uno" ,
	'visiting_address' => 'Sandhaugen 1',
	'box_no' => 12345 ,	
	'city' => "Oslo" ,
	'contact_person' => "Jostein Skaar"	
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

$organisation2 = Organisation::create(array(
	'name' => "Organisasjon nummer doss" ,
	'visiting_address' => 'Hauglandsplass 13',
	'box_no' => 23456 ,	
	'city' => "Bergen" ,
	'contact_person' => "Jostein Skaar"	
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

$organisation3 = Organisation::create(array(
	'name' => "Organisasjon nummer drei" ,
	'visiting_address' => 'Gategate 19',
	'box_no' => 34567 ,	
	'city' => "Kristiansand" ,
	'contact_person' => "Jostein Skaar"	
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

$project1 = Project::create(array(
	'title' => "Prosjet nummer ein",
	'organisation_id' => $organisation2->id,
	'category_id' =>  $category3->id,	
	'district_id' => $district111->id,
	'location' => "Lokasjon uno",
	'has_industrial_waste_water' => $code41->id
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

$project2 = Project::create(array(
	'title' => "Prosjet nummer two",
	'organisation_id' => $organisation1->id,
	'category_id' =>  $category6->id,	
	'district_id' => $district3->id,
	'location' => "Lokasjon dos",
	'has_industrial_waste_water' => $code41->id
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

$project3 = Project::create(array(
	'title' => "Prosjet nummer tress",
	'organisation_id' => $organisation1->id,
	'category_id' =>  $category8->id,	
	'district_id' => $district11->id,
	'location' => "Lokasjon tress",
	'has_industrial_waste_water' => $code41->id
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

$project4 = Project::create(array(
	'title' => "Prosjet nummer fjers",
	'organisation_id' => $organisation1->id,
	'category_id' =>  $category9->id,	
	'district_id' => $district11->id,
	'location' => "Lokasjon firr",
	'has_industrial_waste_water' => $code40->id
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

*/
    }

}