<?php

// info begin
// Generated by script 2015-09-24 13:53:57, 
// based on file "N:\Felles\Forurensning\2. Internasjonalt arbeid\2012. Uganda\Kravspek\Tabeller\Supporting tables version 1.26.xlsx".
// info end

use Illuminate\Database\Seeder;
use \App\User;
use \App\Role;

class TestUserSeeder extends Seeder
{

    public function run()
    {
        $isProduction = App::environment() === "production";
        if ($isProduction)
        {
            throw new Exception("Can't run this in production");
        }

        $role1 = Role::find(1);
        $role2 = Role::find(2);
        $role3 = Role::find(3);
        $role4 = Role::find(4);
        $role5 = Role::find(5);
        $role6 = Role::find(6);
        $role7 = Role::find(7);
        $role8 = Role::find(8);

//        $userJostein = User::where('initials', '=', 'josska')->first();
//        DB::table('role_user')->where('user_id', '=', $userJostein->id)->delete();
//        $userJostein->attachRoles([$role1, $role2, $role3, $role4, $role5, $role6, $role7, $role8]);
//
//        $userJohnny = User::where('initials', '=', 'johaue')->first();
//        DB::table('role_user')->where('user_id', '=', $userJohnny->id)->delete();
//        $userJohnny->attachRoles([$role1, $role2, $role3, $role4, $role5, $role6, $role7, $role8]);

        try
        {
            $user1 = User::create(array(
                'initials' => "fraekl",
                'name' => "Frank Eklo",
                'job_position_code' => "MILJODIR",
                'job_position_name' => "Senior advisor",
                'email' => "frank.eklo@miljodir.no",
                'password' => Hash::make('franktest')
            ));
            $user1->attachRoles([$role1, $role2, $role3, $role7]);
        } catch (Exception $ex)
        {
            print("fraekl exists\n");
        }

        try
        {

            $user2 = User::create(array(
                'initials' => "raglar",
                'name' => "Ragnvald Larsen",
                'job_position_code' => "MILJODIR",
                'job_position_name' => "Senior engineer",
                'email' => "ragnvald.larsen@miljodir.no",
                'password' => Hash::make('ragnvaldtest')
            ));
            $user2->attachRoles([$role1, $role2, $role3, $role7]);
        } catch (Exception $ex)
        {
            print("raglar exists\n");
        }

        try
        {

            $user3 = User::create(array(
                'initials' => "kjepet",
                'name' => "Kjetil Petterson",
                'job_position_code' => "MILJODIR",
                'job_position_name' => "Senior engineer",
                'email' => "kjetil.pettersson@miljodir.no",
                'password' => Hash::make('kjetiltest')
            ));
            $user3->attachRoles([$role1, $role2, $role3, $role7]);
        } catch (Exception $ex)
        {
            print("kjepet exists\n");
        }

        try
        {

            $user4 = User::create(array(
                'initials' => "kriein",
                'name' => "Kristin Eine",
                'job_position_code' => "MILJODIR",
                'job_position_name' => "Chief engineer",
                'email' => "kristin.eine@miljodir.no",
                'password' => Hash::make('kristintest')
            ));
            $user4->attachRoles([$role1, $role2, $role3, $role7]);
        } catch (Exception $ex)
        {
            print("kriein exists\n");
        }

        try
        {

            $user4 = User::create(array(
                'initials' => "svesko",
                'name' => "Svein Grotli Skogen",
                'job_position_code' => "MILJODIR",
                'job_position_name' => "Senior advisor",
                'email' => "svein.grotli.skogen@miljodir.no",
                'password' => Hash::make('sveintest')
            ));
            $user4->attachRoles([$role1, $role2, $role3, $role7]);
        } catch (Exception $ex)
        {
            print("svesko exists\n");
        }
    }
}