<?php

return  [
    [
        "id" => 37,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-12T09:59:51.775391+03:00",
        "updated_at" => "2024-03-12T09:59:51.775409+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "General.",
        "description" => "General.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 36,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-12T09:43:51.378855+03:00",
        "updated_at" => "2024-03-12T09:43:51.378873+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Waste management facilities.",
        "description" => "Waste management facilities.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 35,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-11T12:00:16.705688+03:00",
        "updated_at" => "2024-03-11T12:00:16.705719+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Petroleum operations.",
        "description" => "Petroleum operations.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 34,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-11T11:57:35.284046+03:00",
        "updated_at" => "2024-03-11T11:57:35.284066+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Assembling plants.",
        "description" => "Assembling plants.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 33,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-08T19:41:27.394627+03:00",
        "updated_at" => "2024-03-08T19:41:27.394651+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Manufacturing of non-metallic products.",
        "description" => "Manufacturing of non-metallic products.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 32,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Chemical, safety, radiation and pollution",
        "created_at" => "2024-03-07T17:08:33.905913+03:00",
        "updated_at" => "2024-03-07T17:08:33.905934+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Metallurgy.",
        "description" => "Metallurgy.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 3
    ],
    [
        "id" => 31,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Chemical, safety, radiation and pollution",
        "created_at" => "2024-03-07T17:05:57.138240+03:00",
        "updated_at" => "2024-03-07T17:05:57.138270+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Tanning and leather industry.",
        "description" => "Tanning and leather industry.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 3
    ],
    [
        "id" => 30,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Chemical, safety, radiation and pollution",
        "created_at" => "2024-03-07T16:44:23.348932+03:00",
        "updated_at" => "2024-03-07T16:44:23.348954+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Textile industry.",
        "description" => "Textile industry.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 3
    ],
    [
        "id" => 29,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-07T16:40:28.361929+03:00",
        "updated_at" => "2024-03-07T16:40:28.361950+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Wood industries.",
        "description" => "Wood industries.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 28,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-07T16:31:54.901717+03:00",
        "updated_at" => "2024-03-07T16:31:54.901739+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Hotel, tourism and recreational development.",
        "description" => "Hotel, tourism and recreational development.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 27,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-07T16:20:39.683946+03:00",
        "updated_at" => "2024-03-07T16:20:39.683967+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Extraction of non-mineral products.",
        "description" => "Extraction of non-mineral products.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 26,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Chemical, safety, radiation and pollution",
        "created_at" => "2024-03-07T16:14:02.575130+03:00",
        "updated_at" => "2024-03-07T16:14:02.575156+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Chemical industry.",
        "description" => "Chemical industry.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 3
    ],
    [
        "id" => 25,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Chemical, safety, radiation and pollution",
        "created_at" => "2024-03-07T16:10:14.197361+03:00",
        "updated_at" => "2024-03-07T16:10:14.197384+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Electrical and electronics industry.",
        "description" => "Electrical and electronics industry.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 3
    ],
    [
        "id" => 24,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Oil, gas and Minerals",
        "created_at" => "2024-03-07T16:03:45.107068+03:00",
        "updated_at" => "2024-03-07T16:03:45.107099+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Mining industry and mineral processing.",
        "description" => "Mining industry and mineral processing.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 1
    ],
    [
        "id" => 23,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-07T14:24:53.139109+03:00",
        "updated_at" => "2024-03-07T14:24:53.139129+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Forestry.",
        "description" => "Forestry.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 22,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-06T13:10:05.197409+03:00",
        "updated_at" => "2024-03-06T13:10:05.197440+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Nature conservation areas.",
        "description" => "Nature conservation areas.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 21,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Chemical, safety, radiation and pollution",
        "created_at" => "2024-03-06T12:43:52.643905+03:00",
        "updated_at" => "2024-03-06T12:43:52.643931+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Food and beverage industry.",
        "description" => "Food and beverage industry.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 3
    ],
    [
        "id" => 20,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-06T11:05:54.752626+03:00",
        "updated_at" => "2024-03-06T11:05:54.752647+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Agricultural investments, livestock, range management and fisheries.",
        "description" => "Agricultural investments, livestock, range management and fisheries.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 19,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-06T11:00:40.345028+03:00",
        "updated_at" => "2024-03-06T11:00:40.345047+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Housing and urban development.",
        "description" => "Housing and urban development.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 18,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-06T10:18:11.949905+03:00",
        "updated_at" => "2024-03-06T10:18:11.949925+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Utilisation of water resources and water supply.",
        "description" => "Utilisation of water resources and water supply.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 17,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-06T10:02:45.923003+03:00",
        "updated_at" => "2024-03-06T10:02:45.923030+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Exploration and power generation, transmission and distribution infrastructure.",
        "description" => "Exploration and power generation, transmission and distribution infrastructure.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 16,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-06T09:59:44.115301+03:00",
        "updated_at" => "2024-03-06T09:59:44.115320+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Communications facilities.",
        "description" => "Communications facilities.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 15,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-03-06T09:20:18.746432+03:00",
        "updated_at" => "2024-03-22T13:26:24.878066+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Transport, transportation equipment and related infrastructure.",
        "description" => "Transport, transportation equipment and related infrastructure.",
        "type" => "esia",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 14,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-02-09T11:23:01.903652+03:00",
        "updated_at" => "2024-02-09T11:23:01.903673+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "General.",
        "description" => "General.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 13,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-02-09T11:10:30.681114+03:00",
        "updated_at" => "2024-02-09T11:10:30.681137+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Petroleum activities and operations.",
        "description" => "Petroleum activities and operations.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 12,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-02-09T11:07:37.076230+03:00",
        "updated_at" => "2024-02-09T11:07:37.076251+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Extraction of non-mineral products.",
        "description" => "Extraction of non-mineral products.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 11,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Oil, gas and Minerals",
        "created_at" => "2024-02-09T11:05:05.652881+03:00",
        "updated_at" => "2024-02-09T11:05:05.652904+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Mining industry and mineral processing.",
        "description" => "Mining industry and mineral processing.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 1
    ],
    [
        "id" => 10,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Chemical, safety, radiation and pollution",
        "created_at" => "2024-02-09T11:03:44.554649+03:00",
        "updated_at" => "2024-02-09T11:03:44.554672+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Metallurgy.",
        "description" => "Metallurgy.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 3
    ],
    [
        "id" => 9,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-02-09T10:58:38.578502+03:00",
        "updated_at" => "2024-02-09T10:58:38.578519+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Hotel, tourism and recreational development.",
        "description" => "Hotel, tourism and recreational development.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 8,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-02-09T10:54:40.375093+03:00",
        "updated_at" => "2024-02-09T10:54:40.375119+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Nature conservation areas.",
        "description" => "Nature conservation areas.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 7,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Chemical, safety, radiation and pollution",
        "created_at" => "2024-02-08T16:53:35.172422+03:00",
        "updated_at" => "2024-02-08T16:53:35.172446+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Food and beverage industry.",
        "description" => "Food and beverage industry.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 3
    ],
    [
        "id" => 6,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-02-08T16:45:22.756766+03:00",
        "updated_at" => "2024-02-08T16:45:22.756790+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Agriculture, livestock, range management and fisheries.",
        "description" => "Agriculture, livestock, range management and fisheries.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 5,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-02-08T16:38:55.765484+03:00",
        "updated_at" => "2024-02-08T16:38:55.765513+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Housing and urban development.",
        "description" => "Housing and urban development.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 4,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-02-08T16:32:32.939399+03:00",
        "updated_at" => "2024-02-08T16:32:32.939429+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Utilisation of water resources and water supply.",
        "description" => "Utilisation of water resources and water supply.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 3,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-02-08T16:11:06.914853+03:00",
        "updated_at" => "2024-02-08T16:11:06.914876+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Exploration and power generation, transmission and distribution infrastructure.",
        "description" => "Exploration and power generation, transmission and distribution
        infrastructure.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 2,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-02-08T16:07:10.015537+03:00",
        "updated_at" => "2024-02-08T16:07:10.015559+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Communications facilities.",
        "description" => "Communications facilities.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ],
    [
        "id" => 1,
        "department_name" => "Department of Environment Compliance",
        "division_name" => "Division of Environment assessment",
        "created_at" => "2024-02-08T15:55:36.251003+03:00",
        "updated_at" => "2024-02-08T15:55:36.251033+03:00",
        "declaration" => false,
        "deleted" => false,
        "name" => "Transport, transportation equipment and related infrastructure.",
        "description" => "Transport, transportation equipment and related infrastructure.",
        "type" => "pb",
        "created_by" => null,
        "department" => 2,
        "department_division" => 2
    ]
];
