<?php

// info begin
// Generated by script 2015-08-31 13:31:28, 
// based on file "N:\Felles\Forurensning\2. Internasjonalt arbeid\2012. Uganda\Kravspek\Tabeller\Databasefields for EIA database NEMA version 0.53.xlsx".
// info end

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class TablesAuditAndInspections extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
			DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        Schema::dropIfExists('audits_inspections', function(Blueprint $table){});

// up begin
Schema::create('audits_inspections', function(Blueprint $table)
{
	$table->increments('id');
	$table->integer('year')->unsigned()->nullable();
	$table->integer('number')->unsigned()->nullable();
	$table->integer('type')->unsigned()->nullable();
	$table->boolean('coordinated')->default(false)->nullable();
	$table->boolean('advance_notice')->default(false)->nullable();
	$table->date('date_carried_out')->nullable();
	$table->integer('days')->unsigned()->nullable();
	$table->string('findings', 2000)->nullable();
	$table->string('recommendations', 2000)->nullable();
	$table->date('date_action_taken')->nullable();
	$table->integer('action_taken')->unsigned()->nullable();
	$table->string('external_participants', 255)->nullable();
	$table->integer('timeframe')->unsigned()->nullable();
	$table->date('date_deadline')->nullable();
	$table->date('date_received')->nullable();
	$table->date('date_closing')->nullable();
	$table->integer('project_id')->unsigned()->nullable(); 
	$table->foreign('project_id')->references('id')->on('projects');
	$table->integer('status')->unsigned()->nullable();
	$table->string('remarks', 2000)->nullable();
	$table->softDeletes();
	$table->string('created_by', 255)->nullable();
	$table->string('updated_by', 255)->nullable();
	$table->timestamps();
});


Schema::create('audits_inspections_lead_agencies', function(Blueprint $table)
{
	$table->increments('id');
	$table->integer('audit_inspection_id')->unsigned()->nullable(); 
	$table->foreign('audit_inspection_id')->references('id')->on('audits_inspections');
	$table->integer('lead_agency_id')->unsigned()->nullable(); 
	$table->foreign('lead_agency_id')->references('id')->on('lead_agencies');
});


Schema::create('audits_inspections_personnel', function(Blueprint $table)
{
	$table->increments('id');
	$table->integer('audit_inspection_id')->unsigned()->nullable(); 
	$table->foreign('audit_inspection_id')->references('id')->on('audits_inspections');
	$table->integer('user_id')->unsigned()->nullable(); 
	$table->foreign('user_id')->references('id')->on('users');
});


// up end

		DB::statement('SET FOREIGN_KEY_CHECKS=1;');
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		DB::statement('SET FOREIGN_KEY_CHECKS=0;');
// down begin
	Schema::dropIfExists('audits_inspections', function(Blueprint $table){});
	Schema::dropIfExists('audits_inspections_lead_agencies', function(Blueprint $table){});
	Schema::dropIfExists('audits_inspections_personnel', function(Blueprint $table){});
// down end
	DB::statement('SET FOREIGN_KEY_CHECKS=1;');
	}	

}
