<?php

// info begin
// Generated by script 2014-08-14 23:27:46, 
// based on file "C:\Dropbox\Deling\Nema\Supporting tables version 1.9.xlsx".
// info end
 
class ExcelDataTableSeeder extends Seeder {
 
    public function run()
    {
        DB::table('users')->truncate();
        DB::table('assigned_roles')->truncate();
        DB::table('permission_role')->truncate();
        DB::table('roles')->truncate();
        DB::table('permissions')->truncate();        
        DB::table('categories')->truncate();
        DB::table('codes')->truncate();
        DB::table('districts')->truncate();
        //DB::table('practitioner_certificates')->truncate();
        //DB::table('practitioners')->truncate();
        //DB::table('organisations')->truncate();
        //DB::table('projects')->truncate();
        //DB::table('additional_districts')->truncate();

        
        //$permission1 = Permission::create(array('name' => 'Rettighet 1', 'display_name' => 'Rettighet 1'));
        //$permission2 = Permission::create(array('name' => 'Rettighet 2', 'display_name' => 'Rettighet 2'));
        //$role1->attachPermission($permission1);
        //$role2->attachPermission($permission1);
        //$role2->attachPermission($permission2);


        // seed begin
$user1 = User::create(array(
	'initials' => "awinyi" ,
	'full_name' => "Alex Winyi" ,
	'job_position_code' => "EIAO" ,
	'job_position_name' => "Evironmental Impact Assessment Officer" ,
	'email' => "awinyi@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user2 = User::create(array(
	'initials' => "bbirungi" ,
	'full_name' => "Bonny Birungi" ,
	'job_position_code' => "DS" ,
	'job_position_name' => "Departmental Secretary" ,
	'email' => "kbirungi@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user3 = User::create(array(
	'initials' => "dlufafa" ,
	'full_name' => "Dick Lufafa" ,
	'job_position_code' => "EAMO-1" ,
	'job_position_name' => "Environmental Audits Monitoring Officer" ,
	'email' => "dlufafa@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user4 = User::create(array(
	'initials' => "enidt" ,
	'full_name' => "Enid Turyahikayo" ,
	'job_position_code' => "EAMO" ,
	'job_position_name' => "Environmental Audits and Monitoring Officer" ,
	'email' => "enidt@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user5 = User::create(array(
	'initials' => "fbagoora" ,
	'full_name' => "Festus Bagoora" ,
	'job_position_code' => "NRM(S&L)" ,
	'job_position_name' => "Natural Resources Management Specialist (Soils & Land Use)" ,
	'email' => "fbagoora@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user6 = User::create(array(
	'initials' => "fogwal" ,
	'full_name' => "Francis Ogwal" ,
	'job_position_code' => "NRM(B&R)" ,
	'job_position_name' => "Natural Resources Management Specialist (Bio/Range Lands)" ,
	'email' => "fogwal@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user7 = User::create(array(
	'initials' => "fonyai" ,
	'full_name' => "Fred Onyai" ,
	'job_position_code' => "IMES" ,
	'job_position_name' => "Internal Monitoring and Evaluation Specialist" ,
	'email' => "fonyai@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user8 = User::create(array(
	'initials' => "gkitutu" ,
	'full_name' => "Goreti K. Kitutu" ,
	'job_position_code' => "EISS" ,
	'job_position_name' => "Environmental Information Systems Specialist" ,
	'email' => "gkitutu@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user9 = User::create(array(
	'initials' => "glubega" ,
	'full_name' => "George Lubega " ,
	'job_position_code' => "NRM(Aq)" ,
	'job_position_name' => "Natural Resources Management Specialist (Aquatic)" ,
	'email' => "glubega@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user10 = User::create(array(
	'initials' => "gsawula" ,
	'full_name' => "Gerald Sawula" ,
	'job_position_code' => "DED" ,
	'job_position_name' => "Deputy Executive Director" ,
	'email' => "gsawula@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user11 = User::create(array(
	'initials' => "hnamara" ,
	'full_name' => "Harriet Namara" ,
	'job_position_code' => "EIAA" ,
	'job_position_name' => "Environmental Impact Assessment Assistant" ,
	'email' => "hnamara@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user12 = User::create(array(
	'initials' => "iintujju" ,
	'full_name' => "Isaac I.G. Ntujju" ,
	'job_position_code' => "SEI" ,
	'job_position_name' => "Senior Environmental Inspector" ,
	'email' => "iigntujju@nemaug.org" ,
	'password' => Hash::make('isaac')            
));

$user13 = User::create(array(
	'initials' => "inamuleme" ,
	'full_name' => "Immaculate Namuleme " ,
	'job_position_code' => "EAIMA" ,
	'job_position_name' => "Environmental Assessment and Information Monitoring Assistant " ,
	'email' => "inamuleme@nemaug.org" ,
	'password' => Hash::make('immaculate')            
));

$user14 = User::create(array(
	'initials' => "jkagoda" ,
	'full_name' => "Joy Kagoda" ,
	'job_position_code' => "SPS" ,
	'job_position_name' => "Senior Personal Secretary ED" ,
	'email' => "jkagoda@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user15 = User::create(array(
	'initials' => "jkutesakwe" ,
	'full_name' => "Jeniffer Kutesakwe" ,
	'job_position_code' => "LT" ,
	'job_position_name' => "Laboratory Technician" ,
	'email' => "jkutesakwe@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user16 = User::create(array(
	'initials' => "maanyu" ,
	'full_name' => "Margaret Aanyu " ,
	'job_position_code' => "EIAC" ,
	'job_position_name' => "Environmental Impact Assesment Coordinator" ,
	'email' => "maanyu@nemaug.org" ,
	'password' => Hash::make('margaret')            
));

$user17 = User::create(array(
	'initials' => "mmubangizi" ,
	'full_name' => "Matia Mubangizi" ,
	'job_position_code' => "EAA" ,
	'job_position_name' => "Environmental Audits Assistant" ,
	'email' => "mmubangizi@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user18 = User::create(array(
	'initials' => "naisha" ,
	'full_name' => "Aisha Nakanwaji " ,
	'job_position_code' => "RA" ,
	'job_position_name' => "Registry Assistant" ,
	'email' => "naisha@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user19 = User::create(array(
	'initials' => "nallimadi" ,
	'full_name' => "Nancy Allimadi" ,
	'job_position_code' => "EI" ,
	'job_position_name' => "Environmental Inspector" ,
	'email' => "nallimadi@nemaug.org" ,
	'password' => Hash::make('nancy')            
));

$user20 = User::create(array(
	'initials' => "nobbo" ,
	'full_name' => "Naome Obbo " ,
	'job_position_code' => "EIAO" ,
	'job_position_name' => "Environmental Impact Assessment officer" ,
	'email' => "nobbo@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user21 = User::create(array(
	'initials' => "pkato" ,
	'full_name' => "Phillip Kato" ,
	'job_position_code' => "NA" ,
	'job_position_name' => "Network Administrator" ,
	'email' => "pkato@nemaug.org" ,
	'password' => Hash::make('phillip')            
));

$user22 = User::create(array(
	'initials' => "pnsereko" ,
	'full_name' => "Patience Nsereko" ,
	'job_position_code' => "EMO" ,
	'job_position_name' => "Environmental Monitoring Officer-Oil & Gas" ,
	'email' => "pnsereko@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user23 = User::create(array(
	'initials' => "rmugambwa" ,
	'full_name' => "Richard Mugambwa" ,
	'job_position_code' => "PM-MSW" ,
	'job_position_name' => "Project Manager-Municipal Solid Waste" ,
	'email' => "rmugambwa@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user24 = User::create(array(
	'initials' => "rnamara" ,
	'full_name' => "Rhona Namara" ,
	'job_position_code' => "SPS" ,
	'job_position_name' => "Senior Personal Assistant DED" ,
	'email' => "rnamara@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user25 = User::create(array(
	'initials' => "tkiwanuka" ,
	'full_name' => "Tonny Kiwanuka" ,
	'job_position_code' => "EIAA" ,
	'job_position_name' => "Environmental Impact Assessment Assistant" ,
	'email' => "tkiwanuma@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user26 = User::create(array(
	'initials' => "tokurut" ,
	'full_name' => "Tom O. Okurut" ,
	'job_position_code' => "ED" ,
	'job_position_name' => "Executive Director" ,
	'email' => "tokurut@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user27 = User::create(array(
	'initials' => "wayazika" ,
	'full_name' => "Arnold Waiswa Ayazika" ,
	'job_position_code' => "DEMC" ,
	'job_position_name' => "Director Environmental Monitoring and Compliance" ,
	'email' => "wayazika@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user28 = User::create(array(
	'full_name' => "Christian Haugland" ,
	'job_position_code' => "MILJODIR" ,
	'job_position_name' => "System manager" ,
	'email' => "christian.haugland@miljodir.no" ,
	'password' => Hash::make('christian')            
));

$user29 = User::create(array(
	'full_name' => "Torstein Finnesand" ,
	'job_position_code' => "MILJODIR" ,
	'job_position_name' => "System manager" ,
	'email' => "torstein.finnesand@miljodir.no" ,
	'password' => Hash::make('torstein')            
));

$user30 = User::create(array(
	'full_name' => "Jostein Skaar" ,
	'job_position_code' => "MILJODIR" ,
	'job_position_name' => "System developer" ,
	'email' => "jostein.skaar@miljodir.no" ,
	'password' => Hash::make('jostein')            
));

$user31 = User::create(array(
	'initials' => "mnamubiru" ,
	'full_name' => "Mable Namubiru" ,
	'job_position_code' => "EAIMA" ,
	'job_position_name' => "Environmental Assessment and Information Monitoring Assistant" ,
	'email' => "mnamubiru@nemaug.org" ,
	'password' => Hash::make('mable')            
));

$user32 = User::create(array(
	'initials' => "ckasedde" ,
	'full_name' => "Christine Kasedde" ,
	'job_position_code' => "EIAO" ,
	'job_position_name' => "Evironmental Impact Assessment Officer" ,
	'email' => "ckasedde@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$user33 = User::create(array(
	'initials' => "dkibuuka" ,
	'full_name' => "Dan Kibuuka" ,
	'job_position_code' => "EAMA" ,
	'job_position_name' => "Environment Assessment and Monitoring Assistant" ,
	'email' => "dkibuuka@nemaug.org" ,
	'password' => Hash::make('crazypassword12234335')            
));

$district1 = District::create(array(
	'district' => "Abim" ,
	'hasc' => "UG.AI" ,
	'iso' => 317 ,
	'fips' => "UGB6" ,
	'region' => "N"             
));

$district2 = District::create(array(
	'district' => "Adjumani" ,
	'hasc' => "UG.AD" ,
	'iso' => 301 ,
	'fips' => "UG98" ,
	'region' => "N"             
));

$district3 = District::create(array(
	'district' => "Agago" ,
	'hasc' => "UG.AG" ,
	'fips' => "UGE3" ,
	'region' => "N"             
));

$district4 = District::create(array(
	'district' => "Alebtong" ,
	'hasc' => "UG.AL" ,
	'fips' => "UGE4" ,
	'region' => "N"             
));

$district5 = District::create(array(
	'district' => "Amolatar" ,
	'hasc' => "UG.AT" ,
	'iso' => 314 ,
	'fips' => "UGB7" ,
	'region' => "N"             
));

$district6 = District::create(array(
	'district' => "Amudat" ,
	'hasc' => "UG.AZ" ,
	'fips' => "UGE5" ,
	'region' => "N"             
));

$district7 = District::create(array(
	'district' => "Amuria" ,
	'hasc' => "UG.AM" ,
	'iso' => 216 ,
	'fips' => "UGB8" ,
	'region' => "E"             
));

$district8 = District::create(array(
	'district' => "Amuru" ,
	'hasc' => "UG.AY" ,
	'iso' => 319 ,
	'fips' => "UGB9" ,
	'region' => "N"             
));

$district9 = District::create(array(
	'district' => "Apac" ,
	'hasc' => "UG.AQ" ,
	'iso' => 302 ,
	'fips' => "UG99" ,
	'region' => "N"             
));

$district10 = District::create(array(
	'district' => "Arua" ,
	'hasc' => "UG.AX" ,
	'iso' => 303 ,
	'fips' => "UGA1" ,
	'region' => "N"             
));

$district11 = District::create(array(
	'district' => "Budaka" ,
	'hasc' => "UG.BD" ,
	'iso' => 217 ,
	'fips' => "UGC1" ,
	'region' => "E"             
));

$district12 = District::create(array(
	'district' => "Bududa" ,
	'hasc' => "UG.BA" ,
	'iso' => 223 ,
	'fips' => "UGC2" ,
	'region' => "E"             
));

$district13 = District::create(array(
	'district' => "Bugiri" ,
	'hasc' => "UG.BI" ,
	'iso' => 201 ,
	'fips' => "UG66" ,
	'region' => "E"             
));

$district14 = District::create(array(
	'district' => "Buhweju" ,
	'hasc' => "UG.BH" ,
	'fips' => "UGE6" ,
	'region' => "W"             
));

$district15 = District::create(array(
	'district' => "Buikwe" ,
	'hasc' => "UG.BZ" ,
	'fips' => "UGE7" ,
	'region' => "C"             
));

$district16 = District::create(array(
	'district' => "Bukedea" ,
	'hasc' => "UG.BE" ,
	'iso' => 224 ,
	'fips' => "UGC3" ,
	'region' => "E"             
));

$district17 = District::create(array(
	'district' => "Bukomansimbi" ,
	'hasc' => "UG.BM" ,
	'fips' => "UGE8" ,
	'region' => "C"             
));

$district18 = District::create(array(
	'district' => "Bukwa" ,
	'hasc' => "UG.BW" ,
	'iso' => 218 ,
	'fips' => "UGC4" ,
	'region' => "E"             
));

$district19 = District::create(array(
	'district' => "Bulambuli" ,
	'hasc' => "UG.BB" ,
	'fips' => "UGE9" ,
	'region' => "E"             
));

$district20 = District::create(array(
	'district' => "Buliisa" ,
	'hasc' => "UG.BL" ,
	'iso' => 419 ,
	'fips' => "UGC5" ,
	'region' => "W"             
));

$district21 = District::create(array(
	'district' => "Bundibugyo" ,
	'hasc' => "UG.BX" ,
	'iso' => 401 ,
	'fips' => "UG28" ,
	'region' => "W"             
));

$district22 = District::create(array(
	'district' => "Bushenyi" ,
	'hasc' => "UG.BC" ,
	'iso' => 402 ,
	'fips' => "UG29" ,
	'region' => "W"             
));

$district23 = District::create(array(
	'district' => "Busia" ,
	'hasc' => "UG.BU" ,
	'iso' => 202 ,
	'fips' => "UG67" ,
	'region' => "E"             
));

$district24 = District::create(array(
	'district' => "Butaleja" ,
	'hasc' => "UG.BJ" ,
	'iso' => 219 ,
	'fips' => "UGC6" ,
	'region' => "E"             
));

$district25 = District::create(array(
	'district' => "Butambala" ,
	'hasc' => "UG.BT" ,
	'fips' => "UGF1" ,
	'region' => "C"             
));

$district26 = District::create(array(
	'district' => "Buvuma" ,
	'hasc' => "UG.BV" ,
	'fips' => "UGF2" ,
	'region' => "C"             
));

$district27 = District::create(array(
	'district' => "Buyende" ,
	'hasc' => "UG.BY" ,
	'fips' => "UGF3" ,
	'region' => "E"             
));

$district28 = District::create(array(
	'district' => "Dokolo" ,
	'hasc' => "UG.DO" ,
	'iso' => 318 ,
	'fips' => "UGC7" ,
	'region' => "N"             
));

$district29 = District::create(array(
	'district' => "Gomba" ,
	'hasc' => "UG.GM" ,
	'fips' => "UGF4" ,
	'region' => "C"             
));

$district30 = District::create(array(
	'district' => "Gulu" ,
	'hasc' => "UG.GL" ,
	'iso' => 304 ,
	'fips' => "UGA2" ,
	'region' => "N"             
));

$district31 = District::create(array(
	'district' => "Hoima" ,
	'hasc' => "UG.HO" ,
	'iso' => 403 ,
	'fips' => "UG31" ,
	'region' => "W"             
));

$district32 = District::create(array(
	'district' => "Ibanda" ,
	'hasc' => "UG.IB" ,
	'iso' => 416 ,
	'fips' => "UGC8" ,
	'region' => "W"             
));

$district33 = District::create(array(
	'district' => "Iganga" ,
	'hasc' => "UG.IC" ,
	'iso' => 203 ,
	'fips' => "UGA3" ,
	'region' => "E"             
));

$district34 = District::create(array(
	'district' => "Isingiro" ,
	'hasc' => "UG.NG" ,
	'iso' => 417 ,
	'fips' => "UGC9" ,
	'region' => "W"             
));

$district35 = District::create(array(
	'district' => "Jinja" ,
	'hasc' => "UG.JI" ,
	'iso' => 204 ,
	'fips' => "UG33" ,
	'region' => "E"             
));

$district36 = District::create(array(
	'district' => "Kaabong" ,
	'hasc' => "UG.AB" ,
	'iso' => 315 ,
	'fips' => "UGD1" ,
	'region' => "N"             
));

$district37 = District::create(array(
	'district' => "Kabale" ,
	'hasc' => "UG.KA" ,
	'iso' => 404 ,
	'fips' => "UG34" ,
	'region' => "W"             
));

$district38 = District::create(array(
	'district' => "Kabarole" ,
	'hasc' => "UG.BR" ,
	'iso' => 405 ,
	'fips' => "UG79" ,
	'region' => "W"             
));

$district39 = District::create(array(
	'district' => "Kaberamaido" ,
	'hasc' => "UG.KD" ,
	'iso' => 213 ,
	'fips' => "UG80" ,
	'region' => "E"             
));

$district40 = District::create(array(
	'district' => "Kalangala" ,
	'hasc' => "UG.KN" ,
	'iso' => 101 ,
	'fips' => "UG36" ,
	'region' => "C"             
));

$district41 = District::create(array(
	'district' => "Kaliro" ,
	'hasc' => "UG.RO" ,
	'iso' => 220 ,
	'fips' => "UGD2" ,
	'region' => "E"             
));

$district42 = District::create(array(
	'district' => "Kalungu" ,
	'hasc' => "UG.QA" ,
	'fips' => "UGF5" ,
	'region' => "C"             
));

$district43 = District::create(array(
	'district' => "Kampala" ,
	'hasc' => "UG.KM" ,
	'iso' => 102 ,
	'fips' => "UG37" ,
	'region' => "C"             
));

$district44 = District::create(array(
	'district' => "Kamuli" ,
	'hasc' => "UG.QU" ,
	'iso' => 205 ,
	'fips' => "UGA4" ,
	'region' => "E"             
));

$district45 = District::create(array(
	'district' => "Kamwenge" ,
	'hasc' => "UG.KE" ,
	'iso' => 413 ,
	'fips' => "UG81" ,
	'region' => "W"             
));

$district46 = District::create(array(
	'district' => "Kanungu" ,
	'hasc' => "UG.UU" ,
	'iso' => 414 ,
	'fips' => "UG82" ,
	'region' => "W"             
));

$district47 = District::create(array(
	'district' => "Kapchorwa" ,
	'hasc' => "UG.QP" ,
	'iso' => 206 ,
	'fips' => "UGA5" ,
	'region' => "E"             
));

$district48 = District::create(array(
	'district' => "Kasese" ,
	'hasc' => "UG.KS" ,
	'iso' => 406 ,
	'fips' => "UG40" ,
	'region' => "W"             
));

$district49 = District::create(array(
	'district' => "Katakwi" ,
	'hasc' => "UG.KK" ,
	'iso' => 207 ,
	'fips' => "UGA6" ,
	'region' => "E"             
));

$district50 = District::create(array(
	'district' => "Kayunga" ,
	'hasc' => "UG.KY" ,
	'iso' => 112 ,
	'fips' => "UG83" ,
	'region' => "C"             
));

$district51 = District::create(array(
	'district' => "Kibaale" ,
	'hasc' => "UG.KI" ,
	'iso' => 407 ,
	'fips' => "UG41" ,
	'region' => "W"             
));

$district52 = District::create(array(
	'district' => "Kiboga" ,
	'hasc' => "UG.QO" ,
	'iso' => 103 ,
	'fips' => "UG42" ,
	'region' => "C"             
));

$district53 = District::create(array(
	'district' => "Kibuku" ,
	'hasc' => "UG.QB" ,
	'fips' => "UGF6" ,
	'region' => "E"             
));

$district54 = District::create(array(
	'district' => "Kiruhura" ,
	'hasc' => "UG.KH" ,
	'iso' => 418 ,
	'fips' => "UGD3" ,
	'region' => "W"             
));

$district55 = District::create(array(
	'district' => "Kiryandongo" ,
	'hasc' => "UG.QD" ,
	'fips' => "UGF7" ,
	'region' => "W"             
));

$district56 = District::create(array(
	'district' => "Kisoro" ,
	'hasc' => "UG.KR" ,
	'iso' => 408 ,
	'fips' => "UG43" ,
	'region' => "W"             
));

$district57 = District::create(array(
	'district' => "Kitgum" ,
	'hasc' => "UG.QT" ,
	'iso' => 305 ,
	'fips' => "UG84" ,
	'region' => "N"             
));

$district58 = District::create(array(
	'district' => "Koboko" ,
	'hasc' => "UG.OK" ,
	'iso' => 316 ,
	'fips' => "UGD4" ,
	'region' => "N"             
));

$district59 = District::create(array(
	'district' => "Kole" ,
	'hasc' => "UG.QL" ,
	'fips' => "UGF8" ,
	'region' => "N"             
));

$district60 = District::create(array(
	'district' => "Kotido" ,
	'hasc' => "UG.KF" ,
	'iso' => 306 ,
	'fips' => "UGA7" ,
	'region' => "N"             
));

$district61 = District::create(array(
	'district' => "Kumi" ,
	'hasc' => "UG.QM" ,
	'iso' => 208 ,
	'fips' => "UG46" ,
	'region' => "E"             
));

$district62 = District::create(array(
	'district' => "Kween" ,
	'hasc' => "UG.QW" ,
	'fips' => "UGF9" ,
	'region' => "E"             
));

$district63 = District::create(array(
	'district' => "Kyankwanzi" ,
	'hasc' => "UG.QZ" ,
	'fips' => "UGG1" ,
	'region' => "C"             
));

$district64 = District::create(array(
	'district' => "Kyegegwa" ,
	'hasc' => "UG.QG" ,
	'fips' => "UGG2" ,
	'region' => "W"             
));

$district65 = District::create(array(
	'district' => "Kyenjojo" ,
	'hasc' => "UG.QJ" ,
	'iso' => 415 ,
	'fips' => "UG85" ,
	'region' => "W"             
));

$district66 = District::create(array(
	'district' => "Lamwo" ,
	'hasc' => "UG.LM" ,
	'fips' => "UGG3" ,
	'region' => "N"             
));

$district67 = District::create(array(
	'district' => "Lira" ,
	'hasc' => "UG.LL" ,
	'iso' => 307 ,
	'fips' => "UGA8" ,
	'region' => "N"             
));

$district68 = District::create(array(
	'district' => "Luuka" ,
	'hasc' => "UG.LK" ,
	'fips' => "UGG4" ,
	'region' => "E"             
));

$district69 = District::create(array(
	'district' => "Luweero" ,
	'hasc' => "UG.LW" ,
	'iso' => 104 ,
	'fips' => "UGA9" ,
	'region' => "C"             
));

$district70 = District::create(array(
	'district' => "Lwengo" ,
	'hasc' => "UG.LE" ,
	'fips' => "UGG5" ,
	'region' => "C"             
));

$district71 = District::create(array(
	'district' => "Lyantonde" ,
	'hasc' => "UG.LY" ,
	'iso' => 116 ,
	'fips' => "UGD5" ,
	'region' => "C"             
));

$district72 = District::create(array(
	'district' => "Manafwa" ,
	'hasc' => "UG.MW" ,
	'iso' => 221 ,
	'fips' => "UGD6" ,
	'region' => "E"             
));

$district73 = District::create(array(
	'district' => "Masaka" ,
	'hasc' => "UG.MQ" ,
	'iso' => 105 ,
	'fips' => "UG71" ,
	'region' => "C"             
));

$district74 = District::create(array(
	'district' => "Masindi" ,
	'hasc' => "UG.MZ" ,
	'iso' => 409 ,
	'fips' => "UG50" ,
	'region' => "W"             
));

$district75 = District::create(array(
	'district' => "Mayuge" ,
	'hasc' => "UG.MG" ,
	'iso' => 214 ,
	'fips' => "UG86" ,
	'region' => "E"             
));

$district76 = District::create(array(
	'district' => "Mbale" ,
	'hasc' => "UG.ME" ,
	'iso' => 209 ,
	'fips' => "UGB1" ,
	'region' => "E"             
));

$district77 = District::create(array(
	'district' => "Mbarara" ,
	'hasc' => "UG.RR" ,
	'iso' => 410 ,
	'fips' => "UGB2" ,
	'region' => "W"             
));

$district78 = District::create(array(
	'district' => "Mitooma" ,
	'hasc' => "UG.MM" ,
	'fips' => "UGG6" ,
	'region' => "W"             
));

$district79 = District::create(array(
	'district' => "Mityana" ,
	'hasc' => "UG.TY" ,
	'iso' => 114 ,
	'fips' => "UGD8" ,
	'region' => "C"             
));

$district80 = District::create(array(
	'district' => "Moroto" ,
	'hasc' => "UG.MX" ,
	'iso' => 308 ,
	'fips' => "UG88" ,
	'region' => "N"             
));

$district81 = District::create(array(
	'district' => "Moyo" ,
	'hasc' => "UG.MY" ,
	'iso' => 309 ,
	'fips' => "UGB3" ,
	'region' => "N"             
));

$district82 = District::create(array(
	'district' => "Mpigi" ,
	'hasc' => "UG.MJ" ,
	'iso' => 106 ,
	'fips' => "UG89" ,
	'region' => "C"             
));

$district83 = District::create(array(
	'district' => "Mubende" ,
	'hasc' => "UG.MD" ,
	'iso' => 107 ,
	'fips' => "UGB4" ,
	'region' => "C"             
));

$district84 = District::create(array(
	'district' => "Mukono" ,
	'hasc' => "UG.MV" ,
	'iso' => 108 ,
	'fips' => "UG90" ,
	'region' => "C"             
));

$district85 = District::create(array(
	'district' => "Nakapiripirit" ,
	'hasc' => "UG.NI" ,
	'iso' => 311 ,
	'fips' => "UG91" ,
	'region' => "N"             
));

$district86 = District::create(array(
	'district' => "Nakaseke" ,
	'hasc' => "UG.NK" ,
	'iso' => 115 ,
	'fips' => "UGD9" ,
	'region' => "C"             
));

$district87 = District::create(array(
	'district' => "Nakasongola" ,
	'hasc' => "UG.NA" ,
	'iso' => 109 ,
	'fips' => "UG73" ,
	'region' => "C"             
));

$district88 = District::create(array(
	'district' => "Namayingo" ,
	'hasc' => "UG.NY" ,
	'fips' => "UGG7" ,
	'region' => "E"             
));

$district89 = District::create(array(
	'district' => "Namutumba" ,
	'hasc' => "UG.BK" ,
	'iso' => 222 ,
	'fips' => "UGE1" ,
	'region' => "E"             
));

$district90 = District::create(array(
	'district' => "Napak" ,
	'hasc' => "UG.NQ" ,
	'fips' => "UGG8" ,
	'region' => "N"             
));

$district91 = District::create(array(
	'district' => "Nebbi" ,
	'hasc' => "UG.NB" ,
	'iso' => 310 ,
	'fips' => "UG58" ,
	'region' => "N"             
));

$district92 = District::create(array(
	'district' => "Ngora" ,
	'hasc' => "UG.NR" ,
	'fips' => "UGG9" ,
	'region' => "E"             
));

$district93 = District::create(array(
	'district' => "Ntoroko" ,
	'hasc' => "UG.NO" ,
	'fips' => "UGH1" ,
	'region' => "W"             
));

$district94 = District::create(array(
	'district' => "Ntungamo" ,
	'hasc' => "UG.NT" ,
	'iso' => 411 ,
	'fips' => "UG59" ,
	'region' => "W"             
));

$district95 = District::create(array(
	'district' => "Nwoya" ,
	'hasc' => "UG.NW" ,
	'fips' => "UGH2" ,
	'region' => "N"             
));

$district96 = District::create(array(
	'district' => "Maracha" ,
	'hasc' => "UG.MH" ,
	'iso' => 320 ,
	'fips' => "UGD7" ,
	'region' => "N"             
));

$district97 = District::create(array(
	'district' => "Otuke" ,
	'hasc' => "UG.OT" ,
	'fips' => "UGH3" ,
	'region' => "N"             
));

$district98 = District::create(array(
	'district' => "Oyam" ,
	'hasc' => "UG.OY" ,
	'iso' => 321 ,
	'fips' => "UGE2" ,
	'region' => "N"             
));

$district99 = District::create(array(
	'district' => "Pader" ,
	'hasc' => "UG.PR" ,
	'iso' => 312 ,
	'fips' => "UG92" ,
	'region' => "N"             
));

$district100 = District::create(array(
	'district' => "Pallisa" ,
	'hasc' => "UG.PS" ,
	'iso' => 210 ,
	'fips' => "UGB5" ,
	'region' => "E"             
));

$district101 = District::create(array(
	'district' => "Rakai" ,
	'hasc' => "UG.RI" ,
	'iso' => 110 ,
	'fips' => "UG61" ,
	'region' => "C"             
));

$district102 = District::create(array(
	'district' => "Rubirizi" ,
	'hasc' => "UG.RZ" ,
	'fips' => "UGH4" ,
	'region' => "W"             
));

$district103 = District::create(array(
	'district' => "Rukungiri" ,
	'hasc' => "UG.RK" ,
	'iso' => 412 ,
	'fips' => "UG93" ,
	'region' => "W"             
));

$district104 = District::create(array(
	'district' => "Sembabule" ,
	'hasc' => "UG.SE" ,
	'iso' => 111 ,
	'fips' => "UG74" ,
	'region' => "C"             
));

$district105 = District::create(array(
	'district' => "Serere" ,
	'hasc' => "UG.SX" ,
	'fips' => "UGH5" ,
	'region' => "E"             
));

$district106 = District::create(array(
	'district' => "Sheema" ,
	'hasc' => "UG.SH" ,
	'fips' => "UGH6" ,
	'region' => "W"             
));

$district107 = District::create(array(
	'district' => "Sironko" ,
	'hasc' => "UG.SK" ,
	'iso' => 215 ,
	'fips' => "UG94" ,
	'region' => "E"             
));

$district108 = District::create(array(
	'district' => "Soroti" ,
	'hasc' => "UG.ST" ,
	'iso' => 211 ,
	'fips' => "UG95" ,
	'region' => "E"             
));

$district109 = District::create(array(
	'district' => "Tororo" ,
	'hasc' => "UG.TR" ,
	'iso' => 212 ,
	'fips' => "UG76" ,
	'region' => "E"             
));

$district110 = District::create(array(
	'district' => "Wakiso" ,
	'hasc' => "UG.WA" ,
	'iso' => 113 ,
	'fips' => "UG96" ,
	'region' => "C"             
));

$district111 = District::create(array(
	'district' => "Yumbe" ,
	'hasc' => "UG.YU" ,
	'iso' => 313 ,
	'fips' => "UG97" ,
	'region' => "N"             
));

$district112 = District::create(array(
	'district' => "Zombo" ,
	'hasc' => "UG.ZO" ,
	'fips' => "UGH7" ,
	'region' => "N"             
));

$code1 = Code::create(array(
	'description1' => "Approved" ,
	'dropdown_list' => "decision"             
));

$code2 = Code::create(array(
	'description1' => "Rejected" ,
	'dropdown_list' => "decision"             
));

$code3 = Code::create(array(
	'description1' => "Disregarded" ,
	'dropdown_list' => "decision"             
));

$code4 = Code::create(array(
	'description1' => "Re-submitted" ,
	'dropdown_list' => "submission"             
));

$code5 = Code::create(array(
	'description1' => "Final submission" ,
	'dropdown_list' => "submission"             
));

$code6 = Code::create(array(
	'description1' => "Considered for EIA" ,
	'dropdown_list' => "consequence"             
));

$code7 = Code::create(array(
	'description1' => "Likely exemptet from EIA" ,
	'dropdown_list' => "consequence"             
));

$code8 = Code::create(array(
	'description1' => "PB" ,
	'description2' => "Project Briefs" ,
	'value1' => 21 ,
	'dropdown_list' => "document_type"             
));

$code9 = Code::create(array(
	'description1' => "EIATOR" ,
	'description2' => "TORs for EIA" ,
	'value1' => 14 ,
	'dropdown_list' => "document_type"             
));

$code10 = Code::create(array(
	'description1' => "EIA" ,
	'description2' => "EIA Reports" ,
	'value1' => 30 ,
	'dropdown_list' => "document_type"             
));

$code11 = Code::create(array(
	'description1' => "EATOR" ,
	'description2' => "TOR for EA" ,
	'value1' => 14 ,
	'dropdown_list' => "document_type"             
));

$code12 = Code::create(array(
	'description1' => "EA" ,
	'description2' => "Audit Reports" ,
	'value1' => 21 ,
	'dropdown_list' => "document_type"             
));

$code13 = Code::create(array(
	'description1' => "VALUE NOT IN USE" ,
	'is_passive' => 1             
));

$code14 = Code::create(array(
	'description1' => "VALUE NOT IN USE" ,
	'is_passive' => 1             
));

$code15 = Code::create(array(
	'description1' => "PB received" ,
	'dropdown_list' => "eia_status"             
));

$code16 = Code::create(array(
	'description1' => "PB sent to director" ,
	'dropdown_list' => "eia_status"             
));

$code17 = Code::create(array(
	'description1' => "PB sent to EIAC" ,
	'dropdown_list' => "eia_status"             
));

$code18 = Code::create(array(
	'description1' => "PB assigned" ,
	'dropdown_list' => "eia_status"             
));

$code19 = Code::create(array(
	'description1' => "PB sent to LA" ,
	'dropdown_list' => "eia_status"             
));

$code20 = Code::create(array(
	'description1' => "PB conclusion" ,
	'dropdown_list' => "eia_status"             
));

$code21 = Code::create(array(
	'description1' => "TOR received" ,
	'dropdown_list' => "eia_status"             
));

$code22 = Code::create(array(
	'description1' => "TOR sent to director" ,
	'dropdown_list' => "eia_status"             
));

$code23 = Code::create(array(
	'description1' => "TOR sent to EIAC" ,
	'dropdown_list' => "eia_status"             
));

$code24 = Code::create(array(
	'description1' => "TOR assigned" ,
	'dropdown_list' => "eia_status"             
));

$code25 = Code::create(array(
	'description1' => "TOR sent to LA" ,
	'dropdown_list' => "eia_status"             
));

$code26 = Code::create(array(
	'description1' => "TOR conclusion" ,
	'dropdown_list' => "eia_status"             
));

$code27 = Code::create(array(
	'description1' => "EIS received" ,
	'dropdown_list' => "eia_status"             
));

$code28 = Code::create(array(
	'description1' => "EIS sent to DED" ,
	'dropdown_list' => "eia_status"             
));

$code29 = Code::create(array(
	'description1' => "EIS sent to director" ,
	'dropdown_list' => "eia_status"             
));

$code30 = Code::create(array(
	'description1' => "EIS assigned" ,
	'dropdown_list' => "eia_status"             
));

$code31 = Code::create(array(
	'description1' => "EIS sent to LA" ,
	'dropdown_list' => "eia_status"             
));

$code32 = Code::create(array(
	'description1' => "Project Recomondations ready" ,
	'dropdown_list' => "eia_status"             
));

$code33 = Code::create(array(
	'description1' => "Project Decision" ,
	'dropdown_list' => "eia_status"             
));

$code34 = Code::create(array(
	'description1' => "Invoiced" ,
	'dropdown_list' => "eia_status"             
));

$code35 = Code::create(array(
	'description1' => "Invoice paid" ,
	'dropdown_list' => "eia_status"             
));

$code36 = Code::create(array(
	'description1' => "Cert. issued" ,
	'dropdown_list' => "eia_status"             
));

$code37 = Code::create(array(
	'description1' => "Cert. cancelled" ,
	'dropdown_list' => "eia_status"             
));

$code38 = Code::create(array(
	'description1' => "TL" ,
	'description2' => "Team leader" ,
	'dropdown_list' => "practitioner"             
));

$code39 = Code::create(array(
	'description1' => "TM" ,
	'description2' => "Team member" ,
	'dropdown_list' => "practitioner"             
));

$code40 = Code::create(array(
	'description1' => "Yes" ,
	'dropdown_list' => "yes_no"             
));

$code41 = Code::create(array(
	'description1' => "No" ,
	'dropdown_list' => "yes_no"             
));

$code42 = Code::create(array(
	'description1' => "Unknown" ,
	'dropdown_list' => "yes_no"             
));

$code43 = Code::create(array(
	'description1' => "Red" ,
	'dropdown_list' => "grade"             
));

$code44 = Code::create(array(
	'description1' => "Yellow" ,
	'dropdown_list' => "grade"             
));

$code45 = Code::create(array(
	'description1' => "Green" ,
	'dropdown_list' => "grade"             
));

$code46 = Code::create(array(
	'description1' => "Blue" ,
	'dropdown_list' => "grade"             
));

$code47 = Code::create(array(
	'description1' => "Unknown" ,
	'dropdown_list' => "grade"             
));

$code48 = Code::create(array(
	'description1' => "Audit" ,
	'dropdown_list' => "audit_inspection"             
));

$code49 = Code::create(array(
	'description1' => "Inspection" ,
	'dropdown_list' => "audit_inspection"             
));

$code50 = Code::create(array(
	'description1' => "EIA" ,
	'description2' => "Environmental Impact Assesment" ,
	'dropdown_list' => "cert_type"             
));

$code51 = Code::create(array(
	'description1' => "EA" ,
	'description2' => "Environmental Audits" ,
	'dropdown_list' => "cert_type"             
));

$code52 = Code::create(array(
	'description1' => "EP" ,
	'description2' => "Environmental Partnership" ,
	'dropdown_list' => "cert_type"             
));

$code53 = Code::create(array(
	'description1' => "PA" ,
	'description2' => "Partnership" ,
	'dropdown_list' => "practitioner"             
));

$category1 = Category::create(array(
	'Id' => 1 ,
	'description_long' => " Education Facility" ,
	'consequence' => "Considered for EIA"             
));

$category2 = Category::create(array(
	'Id' => 2 ,
	'description_long' => " Energy Production / Distribution" ,
	'consequence' => "Considered for EIA"             
));

$category3 = Category::create(array(
	'Id' => 3 ,
	'description_long' => " Fuel Station" ,
	'consequence' => "Considered for EIA"             
));

$category4 = Category::create(array(
	'Id' => 4 ,
	'description_long' => " Information & Communications Technology" ,
	'consequence' => "Considered for EIA"             
));

$category5 = Category::create(array(
	'Id' => 5 ,
	'description_long' => " Infrastructure - Roads, Housing, Renovations" ,
	'consequence' => "Considered for EIA"             
));

$category6 = Category::create(array(
	'Id' => 6 ,
	'description_long' => " Land-Use Change, Forestry, Agriculture, Livestock" ,
	'consequence' => "Considered for EIA"             
));

$category7 = Category::create(array(
	'Id' => 7 ,
	'description_long' => " Minerals, Mining, Quarry" ,
	'consequence' => "Considered for EIA"             
));

$category8 = Category::create(array(
	'Id' => 8 ,
	'description_long' => " Miscellaneous Assessments - Policy, Plan, Programme" ,
	'consequence' => "Considered for EIA"             
));

$category9 = Category::create(array(
	'Id' => 9 ,
	'description_long' => " Oil and Gas" ,
	'consequence' => "Considered for EIA"             
));

$category10 = Category::create(array(
	'Id' => 10 ,
	'description_long' => " Pest, Vector, Disease Control" ,
	'consequence' => "Considered for EIA"             
));

$category11 = Category::create(array(
	'Id' => 11 ,
	'description_long' => " Processing, Manufacturing Industry" ,
	'consequence' => "Considered for EIA"             
));

$category12 = Category::create(array(
	'Id' => 12 ,
	'description_long' => " Waste Management and Infrastructure" ,
	'consequence' => "Considered for EIA"             
));

$category13 = Category::create(array(
	'Id' => 13 ,
	'description_long' => " Water Supply Systems and Sanitation" ,
	'consequence' => "Considered for EIA"             
));

$category14 = Category::create(array(
	'Id' => 14 ,
	'description_long' => " Water Resources, Wetlands, Fisheries Management" ,
	'consequence' => "Considered for EIA"             
));

$category15 = Category::create(array(
	'Id' => 15 ,
	'description_long' => " Wildlife, Hotels, Leisure, Tourism Facility" ,
	'consequence' => "Considered for EIA"             
));

$category16 = Category::create(array(
	'Id' => 16 ,
	'description_long' => "Clearing and farm construction for individual subsistence smal farms" ,
	'consequence' => "Likely exemptet from EIA"             
));

$category17 = Category::create(array(
	'Id' => 17 ,
	'description_long' => "Construction or repair of individual houses" ,
	'consequence' => "Likely exemptet from EIA"             
));

$category18 = Category::create(array(
	'Id' => 18 ,
	'description_long' => "Minor land use changes in area with slopes less than 20 % including housing construction" ,
	'consequence' => "Likely exemptet from EIA"             
));

$category19 = Category::create(array(
	'Id' => 19 ,
	'description_long' => "Information collection (scientific or educational) exept if it involves use of chemicals or endangered species or alien materials" ,
	'consequence' => "Likely exemptet from EIA"             
));

$category20 = Category::create(array(
	'Id' => 20 ,
	'description_long' => "Transfer of ownership of land or related facilities so long as the general character of the area is not changed" ,
	'consequence' => "Likely exemptet from EIA"             
));

$category21 = Category::create(array(
	'Id' => 21 ,
	'description_long' => "Environmental enforcement actions" ,
	'consequence' => "Likely exemptet from EIA"             
));

$category22 = Category::create(array(
	'Id' => 22 ,
	'description_long' => "Emergency repairs to facilities within the character of its surroundings" ,
	'consequence' => "Likely exemptet from EIA"             
));

$leadagency1 = LeadAgency::create(array(
	'short_name' => "PEPD" ,
	'long_name' => "The Petroleum Exploration and Production Department"             
));

$role1 = Role::create(array(
	'name' => "Role 1" ,
	'name2' => "Registry"             
));

$role2 = Role::create(array(
	'name' => "Role 2" ,
	'name2' => "Coordinator"             
));

$role3 = Role::create(array(
	'name' => "Role 3" ,
	'name2' => "Review"             
));

$role4 = Role::create(array(
	'name' => "Role 4" ,
	'name2' => "Invoicing"             
));

$role5 = Role::create(array(
	'name' => "Role 5" ,
	'name2' => "Decision"             
));

$role6 = Role::create(array(
	'name' => "Role 6" ,
	'name2' => "Practitioner certificate"             
));

$role7 = Role::create(array(
	'name' => "Role 7" ,
	'name2' => "Control"             
));

$role8 = Role::create(array(
	'name' => "Role 8" ,
	'name2' => "System manager"             
));

$user12->attachRole($role6);

$user13->attachRole($role1);

$user16->attachRole($role1);
$user16->attachRole($role2);
$user16->attachRole($role3);

$user21->attachRole($role1);
$user21->attachRole($role2);
$user21->attachRole($role3);
$user21->attachRole($role4);
$user21->attachRole($role5);
$user21->attachRole($role6);
$user21->attachRole($role7);
$user21->attachRole($role8);

$user28->attachRole($role1);
$user28->attachRole($role2);
$user28->attachRole($role3);
$user28->attachRole($role4);
$user28->attachRole($role5);
$user28->attachRole($role6);
$user28->attachRole($role7);
$user28->attachRole($role8);

$user29->attachRole($role1);
$user29->attachRole($role2);
$user29->attachRole($role3);
$user29->attachRole($role4);
$user29->attachRole($role5);
$user29->attachRole($role6);
$user29->attachRole($role7);
$user29->attachRole($role8);

$user30->attachRole($role1);
$user30->attachRole($role2);
$user30->attachRole($role3);
$user30->attachRole($role4);
$user30->attachRole($role5);
$user30->attachRole($role6);
$user30->attachRole($role7);
$user30->attachRole($role8);

$user31->attachRole($role1);

// seed end

/*

$organisation1 = Organisation::create(array(
	'name' => "Organisasjon nummer uno" ,
	'visiting_address' => 'Sandhaugen 1',
	'box_no' => 12345 ,	
	'city' => "Oslo" ,
	'contact_person' => "Jostein Skaar"	
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

$organisation2 = Organisation::create(array(
	'name' => "Organisasjon nummer doss" ,
	'visiting_address' => 'Hauglandsplass 13',
	'box_no' => 23456 ,	
	'city' => "Bergen" ,
	'contact_person' => "Jostein Skaar"	
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

$organisation3 = Organisation::create(array(
	'name' => "Organisasjon nummer drei" ,
	'visiting_address' => 'Gategate 19',
	'box_no' => 34567 ,	
	'city' => "Kristiansand" ,
	'contact_person' => "Jostein Skaar"	
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

$project1 = Project::create(array(
	'title' => "Prosjet nummer ein",
	'organisation_id' => $organisation2->id,
	'category_id' =>  $category3->id,	
	'district_id' => $district111->id,
	'location' => "Lokasjon uno",
	'has_industrial_waste_water' => $code41->id
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

$project2 = Project::create(array(
	'title' => "Prosjet nummer two",
	'organisation_id' => $organisation1->id,
	'category_id' =>  $category6->id,	
	'district_id' => $district3->id,
	'location' => "Lokasjon dos",
	'has_industrial_waste_water' => $code41->id
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

$project3 = Project::create(array(
	'title' => "Prosjet nummer tress",
	'organisation_id' => $organisation1->id,
	'category_id' =>  $category8->id,	
	'district_id' => $district11->id,
	'location' => "Lokasjon tress",
	'has_industrial_waste_water' => $code41->id
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

$project4 = Project::create(array(
	'title' => "Prosjet nummer fjers",
	'organisation_id' => $organisation1->id,
	'category_id' =>  $category9->id,	
	'district_id' => $district11->id,
	'location' => "Lokasjon firr",
	'has_industrial_waste_water' => $code40->id
	,'updated_by' => 'Import'
	,'created_by' => 'Import'
));

*/
    }

}